name: Check Commands in README.md
on: [pull_request]
jobs:
  readme:
    name: Readme
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16

    - name: Check out code
      uses: actions/checkout@v2.3.4

    - name: Start With golang
      run: go build ./cmd/permission && timeout --preserve-status 2s ./permission

    - name: Start With Docker
      run: docker build . --tag openslides-permission && timeout --preserve-status 5s docker run --network host openslides-permission
      env:
        DOCKER_BUILDKIT: 1

    - name: Start With Auto Restart
      run: make build-dev && timeout --preserve-status 2s docker run --network host openslides-permission-dev
      env:
        DOCKER_BUILDKIT: 1

    - name: Test With Golang
      run: go test ./...

    - name: Test With With Make
      run: make run-tests
      env:
        DOCKER_BUILDKIT: 1
